default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: monolog_development
  username: monolog_user
  password: monolog

test:
  <<: *default
  database: monolog_test
  username: monolog_user
  password: monolog

production:
  <<: *default
  database: monolog_production
  username: monolog_user
  password: monolog
